# Generated by Django 3.0.5 on 2021-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('roll_number', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
